config/routes.rb
Rails.application.routes.draw do
  root to: "books#index"

  resources :books, only: %i[index show]
  resources :authors, only: %i[index show]
  resources :genres, only: %i[index show]

  get "/about-us" => "pages#about-us"
  get 'search_results', to: 'search#results', as: 'search_results'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :book_authors
    has_many :books, through: :book_authors, dependent: :destroy

    validates :name, :birth_date, :photo_url, presence: true
    validates :name, uniqueness: true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :book_authors
    has_many :authors, through: :book_authors, dependent: :destroy
    has_many :book_genres
    has_many :genres, through: :book_genres, dependent: :destroy

    validates :title, presence: true
    validates :title, :isbn, uniqueness: true
    validates :page_count, numericality: { only_integers: true }
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/book_genre.rb
class BookGenre < ApplicationRecord
  belongs_to :book
  belongs_to :genre
end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :book_genres
    has_many :books, through: :book_genres, dependent: :destroy

    validates :name, presence: true
    validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
    @books =  @author.books
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.includes(:authors).order(:title).page(params[:page]).per(20)
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    @genres = Genre.includes(:books).all
  end

  def show
    @genre = Genre.find(params[:id])
    @books = @genre.books
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def results
    @query = params[:q]

    if params[:author].present?
      @author = Author.find(params[:author])
      @books = @author.books.where('title LIKE ?', "%#{@query}%")
    else
      @books = Book.where('title LIKE ?', "%#{@query}%")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/authors/index.html.erb
<h1>Authors</h1>
<ul>
    <% @authors.each do |author| %>
        <li>
            <img src="<%= author.photo_url %>" width="65">
            <h3><%= link_to author.name, author %></h3>
        </li>
    <%end%>
</ul>

app/views/authors/show.html.erb
<h1><%= @author.name %></h1>

<img src="<%= @author.photo_url %>">

<p>Birthday: <%= @author.birth_date %></p>
<p><%= @author.bio %></p>
<h3><%= @author.name %>'s <%= @books.count %> books: </h3>
<ul>
    <% @books.each do |book| %>
        <li>
            <img src="<%= book.cover_image_url.nil? ? "/images/no_cover.png": book.cover_image_url %>" width="65" alt="book-cover">
            <h3><%= link_to book.title, book %></h3>
            <h5>by <%= link_to book.authors[0].name, book.authors[0] %></h5>
        </li>
    <%end%>
</ul>

app/views/books/index.html.erb
<h1>Books</h1>
<ul>
    <% @books.each do |book| %>
        <li>
            <img src="<%= book.cover_image_url.nil? ? "/images/no_cover.png": book.cover_image_url %>" width="65" alt="book-cover">
            <h3><%= link_to book.title, book %></h3>
            <h5>by <%= link_to book.authors[0].name, book.authors[0] %></h5>
        </li>
    <%end%>

    <%= paginate @books %>
</ul>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<img src="<%= @book.cover_image_url.nil? ? "/images/no_cover.png": @book.cover_image_url %>" alt="book-cover">

<h2>By <i><%= link_to @book.authors[0].name, @book.authors[0] %></i></h2>
<p>ISBN: <%= @book.isbn %></p>
<p>Published on <%= @book.published_date %>, <%= @book.page_count %> pages</p>
<p>Genres: 
<% @book.genres.each do |genre| %>
    <%= link_to genre.name, genre %>,
<% end %>
</p>
<p><%= @book.synopsis %></p>

app/views/genres/index.html.erb
<h1>Genres</h1>
<ol>
    <% @genres.each do |genre| %>
        <li>
            <h3><%= link_to genre.name, genre %></h3>
            <p><%= genre.books.count %> Books</p>
        </li>
    <%end%>
</ol>

app/views/genres/show.html.erb
<h1><%= @genre.name %></h1>

<ul>
    <% @books.each do |book| %>
        <li>
            <img src="<%= book.cover_image_url.nil? ? "/images/no_cover.png": book.cover_image_url %>" width="65" alt="book-cover">
            <h3><%= link_to book.title, book %></h3>
            <h5>by <%= link_to book.authors[0].name, book.authors[0] %></h5>
        </li>
    <%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <ul>
        <li><%= link_to "Books", root_path %></li>
        <li><%= link_to "Authors", authors_path %></li>
        <li><%= link_to "Genres", genres_path %></li>
        <li><%= link_to "About Us", about_us_path%></li>
      </ul>
    </nav>
    <%= form_tag(search_results_path, method: "get") do %>
      <%= label_tag(:q, "Search:") %>
      <%= text_field_tag(:q) %>
      

      <%= label_tag(:author, "Filter:") %>
      <%= select_tag(:author, options_for_select(Author.all.collect { |c| [c.name, c.id] }, params[:author]), include_blank: true) %>

      <%= submit_tag("Search")%>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about-us.html.erb
<h1>About Us</h1>

<h2>Dataset Description</h2>

<p>For this data project, I have chosen the Open Library API to seed my database. The API contains information on books, authors, and genres. The purpose of this data project is to build a library-esque site using Ruby on Rails.</p>

<h3>Endpoints</h3>
<ul>
    <li><a href="https://openlibrary.org/works/OL45804W.json">Works API</a>: Containing general information on books</li>
    <li><a href="https://openlibrary.org/books/OL7353617M.json">Editions API</a>: Containing specific information on a specific edition</li>
    <li><a href="https://openlibrary.org/authors/OL23919A.json">Author API</a>: Containing information on authors</li>
    <li><a href="https://covers.openlibrary.org/b/isbn/0385472579-S.jpg">Covers API</a>: Containing book covers</li>
</ul>

<h3>Relationship</h3>
<p>The Author endpoint is called first to retrieve general data on the authors. Then, a call is made to the Works API to get the first 50 works written by the author. General information on the books such as titles and genres is captured here. After that, another call is made to the Editions API to get the more specific information on the book such as ISBN, page count, and publish date. There will be calls to the Covers API anytime an image is displayed, whether for an author, or a book.</p>

<h2>ERD</h2>
<img src="/images/ERD.jpg" alt="ERD">

app/views/search/results.html.erb
<ul>
    <% @books.each do |book| %>
        <li>
            <img src="<%= book.cover_image_url.nil? ? "/images/no_cover.png": book.cover_image_url %>" width="65" alt="book-cover">
            <h3><%= link_to book.title, book %></h3>
            <h5>by <%= link_to book.authors[0].name, book.authors[0] %></h5>
        </li>
    <% end %>
</ul>